'use strict';

// CHANGED: Centralized default settings. This is much cleaner.
const DEFAULT_SETTINGS = {
    enable: true,
    global: false,
    enableToggle: true,
    hotkey: 'CTRL F12',
    paranoidhotkey: 'ALT P',
    newPages: 'Uncloak',
    sfwmode: 'SFW',
    savedsfwmode: '',
    opacity1: 0.05,
    opacity2: 0.5,
    collapseimage: false,
    showIcon: true,
    iconType: 'coffee',
    iconTitle: 'Decreased Productivity',
    disableFavicons: false,
    hidePageTitles: false,
    pageTitleText: 'Google Chrome',
    enableStickiness: false,
    maxwidth: 0,
    maxheight: 0,
    showContext: true,
    showUnderline: true,
    removeBold: false,
    showUpdateNotifications: true,
    font: 'Arial',
    customfont: '',
    fontsize: 12,
    s_bg: 'FFFFFF',
    s_link: '000099',
    s_table: 'cccccc',
    s_text: '000000',
    customcss: '',
    whiteList: [],
    blackList: [],
    version: '0'
};